export const INITIATE_GET_ALL_DATA = 'INITIATE_GET_ALL_DATA';
export const GET_ALL_DATA = 'GET_ALL_DATA';
export const INITIATE_GET_YESTERDAY_DATA = 'INITIATE_GET_YESTERDAY_DATA';
export const GET_YESTERDAY_DATA = 'GET_YESTERDAY_DATA';
